modLoader="javafml"
loaderVersion="[34,)"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/bones/issues"

[[mods]]
modId="bones"
version="1.16.5-2.0.0"
displayName="Bones"
displayURL="https://minecraft.curseforge.com/projects/bones"
logoFile="logo.png"
authors="ochotonida"
description='''
Adds a bunch of skeletal mobs
'''

[[dependencies.bones]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"