modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/ochotonida/bones/issues"
displayURL="https://minecraft.curseforge.com/projects/bones"
logoFile="logo.png"
authors="ochotonida"

[[mods]]
modId="bones"
version="1.15.2-1.3.2"
displayName="Bones"
description='''Adds a bunch of new skeletal mobs'''

[[dependencies.bones]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"